version: '2.1'

services:

    nats-streaming:
        image: nats-streaming:latest
        command: "--config '/opt/nats.yml'"
        volumes:
            - ./nats.yml:/opt/nats.yml

    php:
      image: php:7.1-cli
      volumes:
        - .:/app
      entrypoint: php nats.php
      working_dir: /app
